### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by rcerljenko** [s00d/nuxt-i18n-micro#23]
Hi there!

I've come to an error when accessing route that doesn't exist, eg: /foo. It should show nuxt default error page but instead it throws 500 with this stack trace:
```
[nuxt] [request error] [unhandled] [500] Error
  at createRouterError (./node_modules/vue-router/dist/vue-router.mjs:968:23)  
  at Object.resolve (./node_modules/vue-router/dist/vue-router.mjs:1618:23)  
  at Object.resolve (./node_modules/vue-router/dist/vue-router.mjs:3181:38)  
  at getLocalizedRoute (./chunks/build/server.mjs:2026:17)  
  at localeRoute (./chunks/build/server.mjs:2127:16)  
  at ComputedRefImpl.fn (./chunks/build/TLink-CI_YhY0Q.mjs:327:57)  
  at refreshComputed (./node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:355:28)  
  at get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:1550:5)  
  at unref (./node_modules/@vue/reactivity/dist/reactivity.cjs.prod.js:1406:29)  
  at ./chunks/build/TLink-CI_YhY0Q.mjs:332:13
```

**Comment by s00d** [comment]
<img width="1182" alt="image" src="https://github.com/user-attachments/assets/13fbc29f-126a-4ff0-9d60-f59a4864f3f0">
Hello. Everything works without any issues on my project, please provide an example.

**Comment by rcerljenko** [comment]
yes here it is:

https://nuxt3-vercel-kjvo903w0-lloyds-digital.vercel.app

**Comment by s00d** [comment]
I need access to the code to understand something.

**Comment by s00d** [comment]
Closing due to no response.
