### ISSUE TITLE
typecheck error

### ISSUE THREAD

**Issue by kleinpetr** [s00d/nuxt-i18n-micro#73]
Hi

I am facing another typecheck

```
"nuxt": "^3.14.1592",
"nuxt-i18n-micro": "^1.33.0",
"vue-tsc": "^2.1.10",`
"typescript": "~5.6.3",
````

```
ℹ Using 2024-04-03 as fallback compatibility date.                                              4:07:03 PM
node_modules/.pnpm/nuxt-i18n-micro@1.33.0_magicast@0.3.5_rollup@4.27.4_vite@5.4.11_@types+node@22.9.3_terser@5.36.0_/node_modules/nuxt-i18n-micro/dist/runtime/components/i18n-switcher.vue:36:12 - error TS2322: Type 'string | RouteLocationAsRelativeGeneric | RouteLocationAsPathGeneric' is not assignable to type 'RouteLocationRaw | undefined'.
  Type 'RouteLocationAsRelativeGeneric' is not assignable to type 'RouteLocationRaw | undefined'.
    Type 'RouteLocationAsRelativeGeneric' is not assignable to type 'RouteLocationAsRelativeTyped<RouteNamedMap, "index"> | RouteLocationAsRelativeTyped<RouteNamedMap, "localized-index">'.
      Type 'RouteLocationAsRelativeGeneric' is not assignable to type 'RouteLocationAsRelativeTyped<RouteNamedMap, "localized-index">'.
        Types of property 'name' are incompatible.
          Type 'RouteRecordNameGeneric' is not assignable to type '"localized-index" | undefined'.
            Type 'string' is not assignable to type '"localized-index"'.

36           :to="$switchLocaleRoute(locale.code)"
              ~~

  node_modules/.pnpm/nuxt@3.14.1592_@parcel+watcher@2.5.0_@types+node@22.9.3_eslint@9.15.0_jiti@2.4.0__ioredis@5.4_yhky5sugfdpulusp5ejfc4km6e/node_modules/nuxt/dist/app/components/nuxt-link.d.ts:11:5
    11     to?: RouteLocationRaw;
           ~~
    The expected type comes from property 'to' which is declared here on type 'Partial<{}> & Omit<{ readonly to?: RouteLocationRaw | undefined; readonly href?: RouteLocationRaw | undefined; readonly external?: boolean | undefined; ... 12 more ...; readonly viewTransition?: boolean | undefined; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, undefined> & Record<...>'


Found 1 error in node_modules/.pnpm/nuxt-i18n-micro@1.33.0_magicast@0.3.5_rollup@4.27.4_vite@5.4.11_@types+node@22.9.3_terser@5.36.0_/node_modules/nuxt-i18n-micro/dist/runtime/components/i18n-switcher.vue:36


[4:07:08 PM]  ERROR  Command failed with exit code 2: '~/Projects/app/node_modules/.pnpm/vue-tsc@2.1.10_typescript@5.6.3/node_modules/vue-tsc/bin/vue-tsc.js' --noEmit

  at getFinalError (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/index3.mjs:1134:9)
  at makeError (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/index3.mjs:3614:16)
  at getAsyncResult (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/index3.mjs:7841:4)
  at handlePromise (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/index3.mjs:7824:17)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/chunks/typecheck.mjs:81:7)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1648:16)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1639:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.15.0/node_modules/nuxi/dist/shared/nuxi.bd0a2fa0.mjs:1777:7) 



[4:07:08 PM]  ERROR  Command failed with exit code 2: '~/Projects/app/node_modules/.pnpm/vue-tsc@2.1.10_typescript@5.6.3/node_modules/vue-tsc/bin/vue-tsc.js' --noEmit

**Comment by s00d** [comment]
Hello, could you please make a simple example? Unfortunately, I don't get such an error.

**Comment by kleinpetr** [comment]
after playing around it I realize it happens when I've enabled experimental `typedPages`
https://nuxt.com/docs/guide/going-further/experimental-features#typedpages

**Comment by s00d** [comment]
I enabled typedPages in the playground, but unfortunately, it doesn’t show any errors. I uploaded a new version where I fixed a few typing issues, but most likely, the problem is somewhere else.

**Comment by kleinpetr** [comment]
Thanks, here is minimal reproduction :) 

https://stackblitz.com/github/kleinpetr/i18n-typecheck

1. `pnpm i`
2. `pnpm typecheck`

**Comment by kleinpetr** [comment]
it seems that the NuxtLink accepts just `RouteLocationRaw | undefined` but the value used in i18n-switcher for `:to` is typed as `Type 'string | RouteLocationAsRelativeGeneric | RouteLocationAsPathGeneric'` :thinking: 

![image](https://github.com/user-attachments/assets/f90e9e73-1df3-43b5-9da0-598c1fbb992e)

**Comment by s00d** [comment]
Try version v1.33.3 — I just updated the dependencies, and the error disappeared. I’m not sure what the problem was.
